### ISSUE TITLE
Iceweasel 54 isn't working on XP

### ISSUE THREAD

**Issue by c-sanchez** [adonais/libportable#1]
Iceweasel 54 is not working on Windows XP.
(Iceweasel-v54.0.zh_CN_win32_vc14_pgo.7z)

1) executables are still marked to be vista+ only
2) mozglue.dll , mozavutil.dll , lgpllibs.dll, mozavcodec.dll, d3dcompiler47.dll, xul.dll try to import vista+ stuff
3) K32GetModuleInformation not found... XPCOM? (dynamic loaded) again vista+

**Comment by adonais** [comment]
from Iceweasel 54 Windows XP and Vista are no longer supported.
