### ISSUE TITLE
最新的127不能打开

### ISSUE THREAD

**Issue by bigm0re** [adonais/libportable#17]
最新的127自动升级后就打不开了，Couldn't load XPCOM

**Comment by adonais** [comment]
本地无法重现, 解决问题就很麻烦. 等下一个版本试试.

**Comment by adonais** [comment]
> 最新的127自动升级后就打不开了，Couldn't load XPCOM

更新vc2015-2022运行库, 下载目前最新版本,
https://aka.ms/vs/17/release/vc_redist.x64.exe
