### ISSUE TITLE
请教从源码添加模块并编译的细节

### ISSUE THREAD

**Issue by crackself** [adonais/libportable#4]
刚接触Firefox源码编译，按照说明添加对文件进行打补丁，在windows下编译失败。请问源码文件是否直接放置到toolkit/library目录内？
或者这是只适合在Linux下交叉编译的吗？

**Comment by adonais** [comment]
把编译出来的libportable文件分别放在以下目录:
portable64.dll或portable32.dll放入clang编译器的bin目录下.
portable64.lib或portable32.lib放入clang编译器的lib目录下.
portable.h放入clang编译器的include目录下.
如果使用第三方库,是程序开发人员最基本的要求!
