### ISSUE TITLE
火狐在79.0b1或之后的版本运行了injectpe.bat之后，无法启动firefox程序。

### ISSUE THREAD

**Issue by dragonzhao9** [adonais/libportable#5]
在火狐78.0b9或之前的版本都可以兼容，不过到了火狐79.0b1或之后的版本就无法兼容了。在火狐79.0b1或之后的版本运行injectpe.bat了之后，启动了火狐就会弹出“火狐无法启动”的窗口了。

**Comment by dragonzhao9** [comment]
不好意思。
能用了。

**Comment by c-sanchez** [comment]
I'm trying to apply libportable to Firefox 78.0.1 x64 (ES-MX) with libportable (I downloaded the portable_bin.7z from sourceforge)
However when I run the inject.bat this just closes, delete all patch files and closes without makes any change.
But with the x86 version works.

BTW, I think it's better if you leave all the text of injectpe.bat in English.
